spring:
  application:
    name: life-vault
  
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lifevault}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:your-very-long-secret-key-that-is-at-least-512-bits-which-means-64-characters-long-change-this-in-production}
  expiration: 86400000 # 24 hours

encryption:
  key: ${ENCRYPTION_KEY:your-encryption-key-here-change-in-production}

aws:
  region: ${AWS_REGION:us-east-1}
  sns:
    enabled: ${SNS_ENABLED:false}

inactivity:
  check-interval-days: 1 # Check daily for progressive notifications
  grace-period-days: 14 # 2 weeks grace period after inactivity period

cors:
  allowed-origins: ${CORS_ORIGINS:http://localhost:3000}

logging:
  level:
    com.lifevault: DEBUG
    org.springframework.security: DEBUG