version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: lifevault
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./life-vault-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: lifevault
      DB_USERNAME: postgres
      DB_PASSWORD: password
      JWT_SECRET: this-is-a-very-long-secret-key-for-local-development-that-is-at-least-512-bits-64-chars
      ENCRYPTION_KEY: local-encryption-key-that-should-be-at-least-32-characters-long
      MAIL_USERNAME: test@example.com
      MAIL_PASSWORD: test
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      CORS_ORIGINS: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  frontend:
    build: 
      context: ./life-vault-frontend
      dockerfile: Dockerfile.local
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data: